/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import iuran.*;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.*;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import kasir.Control;
import org.openide.util.Exceptions;
import pelajar.Level;
import pelajar.Profil;
import printout.TunggakanBean;
import sak.KasirException;

/**
 *
 * @author Master
 */
public class InputTransactionTunggakanPasca extends javax.swing.JFrame {
    Profil profil;
    private TableModel tableModelTunggakanPasca;
    private TunggakanPasca tunggakanPascaFromDB;
    private List<Integer> tahunTunggakanPasca;
    public ArrayList<Float> iDDAmounts;
    public ArrayList<Float> beasiswaAmounts;
    public ArrayList<Float> beasiswaCostAmounts;
    public ArrayList<Float> tunggakanPascaAmounts;
    private TunggakanPasca tunggakanPascaCurrent;
    private TunggakanPasca tunggakanPascaStoreToDB;
    private float tunggakanPascaDebt;
    private IDD idd;
    private InputTransactionFrameSeparated itfs;
    private final String[] namaBulan = {"JULI", "AGUSTUS", "SEPTEMBER", "OKTOBER", "NOPEMBER", "DESEMBER", "JANUARI", "PEBRUARI", "MARET", "APRIL", "MEI", "JUNI"};
    private float unpaidTunggakanPasca;
    private ComboBoxModel tahunComboBoxModel;
    private String tunggakanTunggakanPascaString = new String("");
    private String tunggakanTunggakanPascaEachAmountString = new String("");
    /**
     * Creates new form InputTransactionTunggakanPasca
     */
    
    public InputTransactionTunggakanPasca(Profil profil, InputTransactionFrameSeparated itfs) {
        this.profil = profil;
        this.itfs = itfs;
        try {
            tableModelTunggakanPasca = buildTunggakanPascaTableModel(profil, profil.currentLevel.tahun);
        } catch (SQLException ex) {
            Exceptions.printStackTrace(ex);
        } catch (KasirException ex) {
            Exceptions.printStackTrace(ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPaneTunggakanPasca = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelTahun = new javax.swing.JLabel();
        jComboBoxTahun = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jUnpaidjTextFieldTunggakanPasca = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableTunggakanPasca = new javax.swing.JTable();
        jButtonBayarTunggakanPasca = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextFieldIDDSaldo = new javax.swing.JFormattedTextField();
        jTextFieldTunggakanPascaDebt = new javax.swing.JFormattedTextField();

        setTitle(org.openide.util.NbBundle.getMessage(InputTransactionTunggakanPasca.class, "InputTransactionTunggakanPasca.title")); // NOI18N

        jPaneTunggakanPasca.setMinimumSize(new java.awt.Dimension(570, 380));
        jPaneTunggakanPasca.setPreferredSize(new java.awt.Dimension(680, 450));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText(org.openide.util.NbBundle.getMessage(InputTransactionTunggakanPasca.class, "InputTransactionTunggakanPasca.jLabel1.text")); // NOI18N

        jLabelTahun.setText(org.openide.util.NbBundle.getMessage(InputTransactionTunggakanPasca.class, "InputTransactionTunggakanPasca.jLabelTahun.text")); // NOI18N

        try{
            tahunComboBoxModel = buildTunggakanPascatahunComboBoxModel(profil);
        }catch(SQLException ex){
            ex.printStackTrace();
        }catch(KasirException ex){
            ex.printStackTrace();
        }
        jComboBoxTahun.setModel(tahunComboBoxModel);
        jComboBoxTahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTahunActionPerformed(evt);
            }
        });
        jComboBoxTahun.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBoxTahunPropertyChange(evt);
            }
        });

        jLabel2.setText(org.openide.util.NbBundle.getMessage(InputTransactionTunggakanPasca.class, "InputTransactionTunggakanPasca.jLabel2.text")); // NOI18N

        jUnpaidjTextFieldTunggakanPasca.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jUnpaidjTextFieldTunggakanPasca.setText(String.valueOf(unpaidTunggakanPasca));
        jUnpaidjTextFieldTunggakanPasca.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jUnpaidjTextFieldTunggakanPasca.setEnabled(false);

        jTableTunggakanPasca.setModel(tableModelTunggakanPasca);
        jTableTunggakanPasca.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableTunggakanPasca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTableTunggakanPascaFocusLost(evt);
            }
        });
        jTableTunggakanPasca.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTableTunggakanPascaPropertyChange(evt);
            }
        });
        jScrollPane5.setViewportView(jTableTunggakanPasca);

        jButtonBayarTunggakanPasca.setText(org.openide.util.NbBundle.getMessage(InputTransactionTunggakanPasca.class, "InputTransactionTunggakanPasca.jButtonBayarTunggakanPasca.text")); // NOI18N
        jButtonBayarTunggakanPasca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBayarTunggakanPascaActionPerformed(evt);
            }
        });

        jLabel3.setText(org.openide.util.NbBundle.getMessage(InputTransactionTunggakanPasca.class, "InputTransactionTunggakanPasca.jLabel3.text")); // NOI18N

        jFormattedTextFieldIDDSaldo.setText(org.openide.util.NbBundle.getMessage(InputTransactionTunggakanPasca.class, "InputTransactionTunggakanPasca.jFormattedTextFieldIDDSaldo.text")); // NOI18N
        jFormattedTextFieldIDDSaldo.setEnabled(false);

        jTextFieldTunggakanPascaDebt.setEditable(false);
        jTextFieldTunggakanPascaDebt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));

        javax.swing.GroupLayout jPaneTunggakanPascaLayout = new javax.swing.GroupLayout(jPaneTunggakanPasca);
        jPaneTunggakanPasca.setLayout(jPaneTunggakanPascaLayout);
        jPaneTunggakanPascaLayout.setHorizontalGroup(
            jPaneTunggakanPascaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneTunggakanPascaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPaneTunggakanPascaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaneTunggakanPascaLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPaneTunggakanPascaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneTunggakanPascaLayout.createSequentialGroup()
                                .addGroup(jPaneTunggakanPascaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPaneTunggakanPascaLayout.createSequentialGroup()
                                        .addComponent(jLabelTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10))
                                    .addGroup(jPaneTunggakanPascaLayout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPaneTunggakanPascaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPaneTunggakanPascaLayout.createSequentialGroup()
                                        .addComponent(jComboBoxTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jUnpaidjTextFieldTunggakanPasca, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPaneTunggakanPascaLayout.createSequentialGroup()
                                        .addComponent(jTextFieldTunggakanPascaDebt, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jFormattedTextFieldIDDSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(36, 36, 36))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPaneTunggakanPascaLayout.createSequentialGroup()
                        .addGroup(jPaneTunggakanPascaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonBayarTunggakanPasca, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPaneTunggakanPascaLayout.setVerticalGroup(
            jPaneTunggakanPascaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneTunggakanPascaLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPaneTunggakanPascaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUnpaidjTextFieldTunggakanPasca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPaneTunggakanPascaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaneTunggakanPascaLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPaneTunggakanPascaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jFormattedTextFieldIDDSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldTunggakanPascaDebt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBayarTunggakanPasca)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneTunggakanPasca, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneTunggakanPasca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxTahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTahunActionPerformed
        // TODO add your handling code here:
        try {
            this.tableModelTunggakanPasca = (DefaultTableModel) buildTunggakanPascaTableModel(this.profil, this.tahunTunggakanPasca.get(jComboBoxTahun.getSelectedIndex()));
            jTableTunggakanPasca.setModel(this.tableModelTunggakanPasca);
            jTextFieldTunggakanPascaDebt.setValue(tunggakanPascaDebt);
        } catch (SQLException ex) {
            ex.printStackTrace();
        } catch (KasirException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jComboBoxTahunActionPerformed

    private void jComboBoxTahunPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBoxTahunPropertyChange
        // TODO add your handling code here:
        try {
            if (this.jComboBoxTahun.getSelectedItem() != null) {
                this.tableModelTunggakanPasca = (DefaultTableModel) buildTunggakanPascaTableModel(this.profil, this.tahunTunggakanPasca.get(jComboBoxTahun.getSelectedIndex()));
                jTableTunggakanPasca.setModel(this.tableModelTunggakanPasca);
                jTextFieldTunggakanPascaDebt.setValue(tunggakanPascaDebt);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Koneksi Error!\r\n".concat(ex.toString()));
        } catch (KasirException ex) {
            JOptionPane.showMessageDialog(rootPane, "TunggakanPasca Belum Di Setting!\r\n".concat(ex.toString()));
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jComboBoxTahunPropertyChange

    private void jTableTunggakanPascaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTableTunggakanPascaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableTunggakanPascaFocusLost

    private void jTableTunggakanPascaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTableTunggakanPascaPropertyChange
        // TODO add your handling code here:
        //IDD, Beasiswa, Beasiswa Cost
        tunggakanPascaAmounts = new ArrayList();
        iDDAmounts = new ArrayList();
        beasiswaAmounts = new ArrayList();
        beasiswaCostAmounts = new ArrayList();
        /////BLOOOOOOOOOOM SELESAIIIIIIIIIIIIIIIIIIII
        int i = 0;
        tunggakanPascaCurrent = new TunggakanPasca();
        tunggakanPascaStoreToDB = new TunggakanPasca();
        ArrayList<Entry> entry = new ArrayList<>();
        if (tunggakanPascaFromDB.entries.size() != 0) {
            for (i = 0; i < jTableTunggakanPasca.getRowCount(); i++) {
                tunggakanPascaCurrent.entries.add((Boolean) jTableTunggakanPasca.getValueAt(i, 2) ? ((tunggakanPascaFromDB.entries.get(i).transactDetailIDs.size() > 0) ? new Entry(i, tunggakanPascaFromDB.entries.get(i).amount, tunggakanPascaFromDB.entries.get(i).debt, tunggakanPascaFromDB.entries.get(i).transactDetailIDs) : new Entry(i, tunggakanPascaFromDB.entries.get(i).amount)) : null);
                //below condition is when jTableTunggakanPasca checkBox is UNCHECK ????
                if (tunggakanPascaCurrent.entries.get(i) == null) {
                    tunggakanPascaStoreToDB.entries.add(null);
                    jTableTunggakanPasca.setValueAt(0f, i, 3);
                    jTableTunggakanPasca.setValueAt(0f, i, 4);
                    jTableTunggakanPasca.setValueAt(0f, i, 5);
                    jTableTunggakanPasca.setValueAt(0f, i, 6);
                    tunggakanPascaAmounts.add(0f);
                    iDDAmounts.add(0f);
                    beasiswaAmounts.add(0f);
                    beasiswaCostAmounts.add(0f);
                    //below is when jTableTunggakanPasca property changed, especially check box is Changed or Editing IDD, Beasiswa, Beasiswa Cost 
                } else if ((tunggakanPascaCurrent.entries.get(i) != null) ^ (tunggakanPascaFromDB.entries.get(i).transactDetailIDs.size() > 0)) {
                    System.out.println("IDD dari db ");
                    if (idd != null) {
                        System.out.println(idd.amount);
                    }
                    tunggakanPascaAmounts.add((Float) jTableTunggakanPasca.getModel().getValueAt(i,3));
                    iDDAmounts.add((Float) jTableTunggakanPasca.getValueAt(i, 4));
                    beasiswaAmounts.add((Float) jTableTunggakanPasca.getValueAt(i, 5));
                    beasiswaCostAmounts.add((Float) jTableTunggakanPasca.getValueAt(i, 6));
                    //jTableTunggakanPasca.setValueAt(tunggakanPascaFromDB.entries.get(i).amount - (iDDAmounts.get(i) + beasiswaAmounts.get(i) + beasiswaCostAmounts.get(i)), i, 3);
                    //tunggakanPascaStoreToDB.entries.add(new Entry(i, tunggakanPascaFromDB.entries.get(i).amount));
                    tunggakanPascaStoreToDB.entries.add(new Entry(i, tunggakanPascaAmounts.get(i)+iDDAmounts.get(i)+beasiswaAmounts.get(i)+beasiswaCostAmounts.get(i)));
                } else {
                    try {
                        if(isTunggakanPascaEnough(tunggakanPascaFromDB.entries.get(i).transactDetailIDs, tunggakanPascaFromDB.entries.get(i).amount)){
                            tunggakanPascaAmounts.add(0f);
                            iDDAmounts.add(0f);
                            beasiswaAmounts.add(0f);
                            beasiswaCostAmounts.add(0f);
                            tunggakanPascaStoreToDB.entries.add(null);
                        }else{
                            tunggakanPascaAmounts.add((Float) jTableTunggakanPasca.getModel().getValueAt(i,3));
                            iDDAmounts.add((Float) jTableTunggakanPasca.getValueAt(i, 4));
                            beasiswaAmounts.add((Float) jTableTunggakanPasca.getValueAt(i, 5));
                            beasiswaCostAmounts.add((Float) jTableTunggakanPasca.getValueAt(i, 6));
                            tunggakanPascaStoreToDB.entries.add(new Entry(i, tunggakanPascaAmounts.get(i)+iDDAmounts.get(i)+beasiswaAmounts.get(i)+beasiswaCostAmounts.get(i)));
                        }
                    } catch (SQLException ex) {
                        Exceptions.printStackTrace(ex);
                    } catch (KasirException ex) {
                        Exceptions.printStackTrace(ex);
                    }
                    

                }
                //tunggakanPascaCurrent.entries.add((Boolean)jTableTunggakanPasca.getValueAt(i,2)? new TunggakanPasca(profil.noInduk, new Level(null,null,null,(Integer)jComboBoxTahun.getSelectedItem()),entry).entries.get(i): null);
                //tunggakanPascaStoreToDB.entries.add(tunggakanPascaCurrent.entries.get(i)==null?null:(((tunggakanPascaCurrent.entries.get(i)!=null)^(tunggakanPascaFromDB.entries.get(i)!=null))? new TunggakanPasca(profil.noInduk, new Level(null,null,null,(int)jComboBoxTahun.getSelectedItem()),entry).entries.get(i):tunggakanPascaCurrent.entries.get(i)));
                //System.out.println("TunggakanPasca Period: "+tunggakanPascaCurrent.entries.get(i).period);
            }
        }
    }//GEN-LAST:event_jTableTunggakanPascaPropertyChange

    private void jButtonBayarTunggakanPascaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBayarTunggakanPascaActionPerformed
        // TODO add your handling code here:
        float tunggakanPascaAmountTemp = 0f;
        for (int i = 0; i < 12; i++) {
            if (tunggakanPascaStoreToDB.entries.get(i) != null) {
                //tunggakanPascaAmountTemp = tunggakanPascaAmountTemp + tunggakanPascaFromDB.entries.get(i).amount;
                tunggakanPascaAmountTemp = tunggakanPascaAmountTemp + (Float)jTableTunggakanPasca.getModel().getValueAt(i,3)
                                +(Float)jTableTunggakanPasca.getModel().getValueAt(i,4)
                                +(Float)jTableTunggakanPasca.getModel().getValueAt(i,5)
                                +(Float)jTableTunggakanPasca.getModel().getValueAt(i,6);
            }
        }
        itfs.jTextFieldTunggakanPascaAmountSimple.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        itfs.jTextFieldTunggakanPascaAmountSimple.setValue(tunggakanPascaAmountTemp);
        try {
            itfs.jTextFieldTunggakanPascaAmountSimple.commitEdit();
        } catch (ParseException ex) {
            Exceptions.printStackTrace(ex);
        }
        itfs.tunggakanPascaCurrent = tunggakanPascaCurrent;
        itfs.tunggakanPascaFromDB = tunggakanPascaFromDB;
        itfs.tunggakanPascaStoreToDB = tunggakanPascaStoreToDB;
        this.setVisible(false);

    }//GEN-LAST:event_jButtonBayarTunggakanPascaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputTransactionFrameSeparated.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputTransactionFrameSeparated.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputTransactionFrameSeparated.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputTransactionFrameSeparated.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                //new InputTransactionTunggakanPasca().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBayarTunggakanPasca;
    private javax.swing.JComboBox jComboBoxTahun;
    private javax.swing.JFormattedTextField jFormattedTextFieldIDDSaldo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelTahun;
    private javax.swing.JPanel jPaneTunggakanPasca;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTableTunggakanPasca;
    private javax.swing.JFormattedTextField jTextFieldTunggakanPascaDebt;
    private javax.swing.JTextField jUnpaidjTextFieldTunggakanPasca;
    // End of variables declaration//GEN-END:variables

    public TableModel buildTunggakanPascaTableModel(Profil profil, int tahun) throws SQLException, KasirException {
       String columnNames[] = {"Bulan", "Biaya TunggakanPasca", "Check Box", "Tunai", "Iuran Dibayar Dimuka", "Beasiswa", "Beasiswa Yayasan"};
       Set<TunggakanPasca> tunggakanPascaFilters = new HashSet<>();
       ArrayList<Entry> entries = new ArrayList<>();
       tunggakanPascaFilters.clear();
       tunggakanPascaFilters.add(new TunggakanPasca(profil.noInduk, new Level(null,null,null,tahun), entries));
       Map<Long, TunggakanPasca> searchResultMap = Control.exactFilterSelectIurans(Iuran.Tipe.TunggakanPasca, tunggakanPascaFilters);
       Object[][] data = new Object[12][7];
       int i = 0;
       final boolean[] canEdit = new boolean [12];
       tunggakanPascaFromDB = new TunggakanPasca();
       float amountTunggakanPascainTable;
       float amountTunggakanPascainTDetail;
       tunggakanPascaDebt = 0f;
       
       //Get Month and Year for calculate IuranPeriodic 12 times a year (Monthly)
       Calendar calendarRunning = Calendar.getInstance();
       int targetMonth = calendarRunning.get(Calendar.MONTH);
       int targetYear = calendarRunning.get(Calendar.YEAR);
       if(targetMonth>5){//JULY - DECEMBER
           targetMonth = targetMonth - 5;
       }else{//JANUARY - JUNE
           targetMonth = targetMonth + 7;
           targetYear = targetYear - 1;
       }
       
       if(searchResultMap.size() > 0){
        for(Map.Entry<Long, TunggakanPasca> entry: searchResultMap.entrySet()){
            for(int j =0 ; j< entry.getValue().entries.size(); j++){
                data[j][0]= namaBulan[j];//entry.getValue().entries.get(j).period;
                data[j][1]= entry.getValue().entries.get(j).amount - calculatePaidTunggakanPasca(entry.getValue().entries.get(j).transactDetailIDs); // ANEH NIH MASA BEGINI, DI KALI DUA SIH?
                amountTunggakanPascainTable = entry.getValue().entries.get(j).amount;
                if(entry.getValue().chargedLevel.tahun < targetYear){
                    tunggakanPascaDebt += entry.getValue().entries.get(j).debt;
                }else if(entry.getValue().chargedLevel.tahun == targetYear && j < targetMonth){
                    tunggakanPascaDebt += entry.getValue().entries.get(j).debt;
                }
                
                //if(jTable2 != null){data[j][2]= jTable2.getModel().getValueAt(j,2);}else{data[j][2]= new Boolean(false);}
                //if(entry.getValue().entries.get(j).transactDetailIDs.size() > 0){
                if(isTunggakanPascaEnough(entry.getValue().entries.get(j).transactDetailIDs, amountTunggakanPascainTable)){        
//                    
                    data[j][2] = new Boolean(true);
                    Float data3 = 0f;
                    Float data4 = 0f;
                    Float data5 = 0f;
                    Float data6 = 0f;
                    
                    for(Long setTDetailIds:entry.getValue().entries.get(j).transactDetailIDs){
                        System.out.println(setTDetailIds + " Set TDetailsID");
                        if(Control.selectTDetail(TransactionDetail.Tipe.TunggakanPascaTransaction, setTDetailIds).paymentMethod == TransactionDetail.PaymentMethod.CASH){
                            data3 += Control.selectTDetail(TransactionDetail.Tipe.TunggakanPascaTransaction, setTDetailIds).amount;
                            data[j][3] = data3;
                        }
                        if(Control.selectTDetail(TransactionDetail.Tipe.TunggakanPascaTransaction, setTDetailIds).paymentMethod == TransactionDetail.PaymentMethod.IDD){
                            data4 += Control.selectTDetail(TransactionDetail.Tipe.TunggakanPascaTransaction, setTDetailIds).amount;
                            data[j][4] = data4;
                        }
                        if(Control.selectTDetail(TransactionDetail.Tipe.TunggakanPascaTransaction, setTDetailIds).paymentMethod == TransactionDetail.PaymentMethod.BEASISWA){
                            data5 += Control.selectTDetail(TransactionDetail.Tipe.TunggakanPascaTransaction, setTDetailIds).amount;
                            data[j][5] = data5;
                        }
                        if(Control.selectTDetail(TransactionDetail.Tipe.TunggakanPascaTransaction, setTDetailIds).paymentMethod == TransactionDetail.PaymentMethod.BEASISWA_COST){
                            data6 += Control.selectTDetail(TransactionDetail.Tipe.TunggakanPascaTransaction, setTDetailIds).amount;
                            data[j][6] = data6;
                        }
                    }
                    if(data[j][3] == null){
                        data[j][3] = 0f;
                    }
                    if(data[j][4] == null){
                        data[j][4] = 0f;
                    }
                    if(data[j][5] == null){
                        data[j][5] = 0f;
                    }
                    if(data[j][6] == null){
                        data[j][6] = 0f;
                    }
                            
                }else{
                    data[j][2] = new Boolean(false);
                    if(entry.getValue().entries.get(j).transactDetailIDs.size() > 0){
                        for(Long setTDetailIds:entry.getValue().entries.get(j).transactDetailIDs){
                            System.out.println(setTDetailIds + " Set TDetailsID");
                            if(Control.selectTDetail(TransactionDetail.Tipe.TunggakanPascaTransaction, setTDetailIds).paymentMethod == TransactionDetail.PaymentMethod.CASH){
                                data[j][3] = Control.selectTDetail(TransactionDetail.Tipe.TunggakanPascaTransaction, setTDetailIds).amount;
                            }
                            if(Control.selectTDetail(TransactionDetail.Tipe.TunggakanPascaTransaction, setTDetailIds).paymentMethod == TransactionDetail.PaymentMethod.IDD){
                                data[j][4] = Control.selectTDetail(TransactionDetail.Tipe.TunggakanPascaTransaction, setTDetailIds).amount;
                            }
                            if(Control.selectTDetail(TransactionDetail.Tipe.TunggakanPascaTransaction, setTDetailIds).paymentMethod == TransactionDetail.PaymentMethod.BEASISWA){
                                data[j][5] = Control.selectTDetail(TransactionDetail.Tipe.TunggakanPascaTransaction, setTDetailIds).amount;
                            }
                            if(Control.selectTDetail(TransactionDetail.Tipe.TunggakanPascaTransaction, setTDetailIds).paymentMethod == TransactionDetail.PaymentMethod.BEASISWA_COST){
                                data[j][6] = Control.selectTDetail(TransactionDetail.Tipe.TunggakanPascaTransaction, setTDetailIds).amount;
                            }
                        }
                        if(data[j][3] == null){
                        data[j][3] = 0f;
                        }
                        if(data[j][4] == null){
                            data[j][4] = 0f;
                        }
                        if(data[j][5] == null){
                            data[j][5] = 0f;
                        }
                        if(data[j][6] == null){
                            data[j][6] = 0f;
                        }
                    }else{
                        data[j][3]=0f;
                        data[j][4]=0f;
                        data[j][5]=0f;
                        data[j][6]=0f;
                    }
                }
                
                tunggakanPascaFromDB.entries.add(entry.getValue().entries.get(j));
                //canEdit[j] = (entry.getValue().entries.get(j).transactDetailIDs.size() > 0);
                
                for(Long id : entry.getValue().entries.get(j).transactDetailIDs){
                    canEdit[j] = Control.selectTDetail(TransactionDetail.Tipe.TunggakanPascaTransaction, id).settled;
                }
                
                
            }
            tunggakanPascaFromDB.id = entry.getValue().id;
            tunggakanPascaFromDB.noInduk = entry.getValue().noInduk;
            tunggakanPascaFromDB.chargedLevel = entry.getValue().chargedLevel;
            i++;
            System.out.println("tunggakanPasca debt "+String.valueOf(tunggakanPascaDebt));
        }
        TableModel tm = new DefaultTableModel(data, columnNames){
            boolean[] chooseEdit = new boolean[]{false,false,true,true,true,true,true};
            
           @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false for editable
                if(!itfs.jDialogTransactionSummary.isVisible()){
                    if((Boolean)getValueAt(row, 2)){
                    //if((Float)getValueAt(row,1) == 0f){
                        if((column == 0 || column ==1)){
                            return column == 2;
                        //return false;
                        }
                        return !canEdit[row];
                    }
                    if((column == 0 && column ==1)|| column == 2){
                            //return column == 2;
                        return chooseEdit[column];
                    }

                    return false;
               }else{
                    return false;
                }
            }
            public Class getColumnClass(int c) {
                return getValueAt(0, c).getClass();
            }
       };
       
       return tm;
       }else{
           TableModel tm = new DefaultTableModel(data, columnNames);
           JOptionPane.showMessageDialog(rootPane, "TunggakanPasca Belum Di Setting!\r\n");
           this.dispose();
           return null;
       }
       
       
    }
    public TableModel buildTunggakanPascaSubmitTableModel(Profil profil, int tahun) throws SQLException, KasirException {
       String columnNames[] = {"Bulan", "Biaya TunggakanPasca", "Check Box", "Tunai", "Iuran Dibayar Dimuka", "Beasiswa", "Beasiswa Yayasan"};
       Object[][] data = new Object[12][7];
       
       final boolean[] canEdit = new boolean [12];
         
        for(int i = 0 ; i < tunggakanPascaCurrent.entries.size(); i++){
                data[i][0]= namaBulan[i];//entry.getValue().entries.get(j).period;
                data[i][1]= tunggakanPascaFromDB.entries.get(i).amount; // ANEH NIH MASA BEGINI, DI KALI DUA SIH?
                if(tunggakanPascaCurrent.entries.get(i) != null){
//                    if(jTableTunggakanPasca != null){
//                        data[j][2]=jTableTunggakanPasca.getValueAt(j,2);
//                    }else{
                        data[i][2] = new Boolean(true);
//                        data[i][3] = tunggakanPascaFromDB.entries.get(i).amount-(iDDAmounts.get(i)+beasiswaAmounts.get(i)+beasiswaCostAmounts.get(i));
                        data[i][3] = tunggakanPascaAmounts.get(i);
                        data[i][4] = iDDAmounts.get(i);
                        data[i][5] = beasiswaAmounts.get(i);
                        data[i][6] = beasiswaCostAmounts.get(i);
//                    }
                }else{
//                    if(jTableTunggakanPasca !=null){
//                        data[j][2]=jTableTunggakanPasca.getValueAt(j,2);
//                    }else{
                        data[i][2] = new Boolean(false);
//                        data[i][3] = tunggakanPascaFromDB.entries.get(i).amount-(iDDAmounts.get(i)+beasiswaAmounts.get(i)+beasiswaCostAmounts.get(i));
                        data[i][3] = tunggakanPascaAmounts.get(i);
                        data[i][4] = iDDAmounts.get(i);
                        data[i][5] = beasiswaAmounts.get(i);
                        data[i][6] = beasiswaCostAmounts.get(i);
//                    }
                }
       }
       
       TableModel tm = new DefaultTableModel(data, columnNames){
            boolean[] chooseEdit = new boolean[]{false,false,true};
            
           @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false for editable
                if(!itfs.jDialogTransactionSummary.isVisible()){
                    if((Boolean)getValueAt(row, 2)){
                        if((column == 0 || column ==1)){
                            return column == 2;
                        //return false;
                        }
                        return !canEdit[row];
                    }
                    if((column == 0 && column ==1)|| column == 2){
                            //return column == 2;
                        return chooseEdit[column];
                    }

                    return false;
               }else{
                    return false;
                }
            }
            public Class getColumnClass(int c) {
                return getValueAt(0, c).getClass();
            }
       };
       
       return tm;
    }
    
private ComboBoxModel buildTunggakanPascatahunComboBoxModel(Profil profil) throws SQLException, KasirException {
       Set<TunggakanPasca> tunggakanPascaFilters = new HashSet<>();
       ArrayList<Entry> entries = new ArrayList();
       tunggakanPascaFilters.add(new TunggakanPasca(profil.noInduk, null, entries));
       Map<Long, TunggakanPasca> searchResultMap = Control.exactFilterSelectIurans(Iuran.Tipe.TunggakanPasca, tunggakanPascaFilters);
       this.tahunTunggakanPasca = new ArrayList<>();
       List<String> tahunAjaran = new ArrayList<>();
       Object[][] data = new Object[searchResultMap.size()][12];
       int i = 0;
       if(searchResultMap.size() > 0){
        for(Map.Entry<Long, TunggakanPasca> entry: searchResultMap.entrySet()){
            data[i][0]= entry.getValue().entries.get(i);
            data[i][1]= entry.getValue().entries.get(i).amount;
            this.tahunTunggakanPasca.add(entry.getValue().chargedLevel.tahun);
            tahunAjaran.add(String.valueOf(entry.getValue().chargedLevel.tahun).concat(" - ").concat(String.valueOf(entry.getValue().chargedLevel.tahun+1)));
            i++;
        }
       }
       calculateUnpaidTunggakanPasca(profil, tahunTunggakanPasca);
       //== bikin tunggakan beans ===
       
       
       //== end bikin tunggakan beans ===
       
       tahunComboBoxModel = new DefaultComboBoxModel(tahunAjaran.toArray());
       return tahunComboBoxModel;
    }

private float calculateUnpaidTunggakanPasca(Profil profil, List<Integer> tahuns) throws SQLException, KasirException {
       Set<TunggakanPasca> tunggakanPascaFilters = new HashSet<>();
       float retVal = 0;
       ArrayList<Entry> entries = new ArrayList<>();
       tunggakanPascaFilters.clear();
       int targetMonth = Calendar.getInstance().get(Calendar.MONTH);
       int targetYear = Calendar.getInstance().get(Calendar.YEAR);
       if(targetMonth>5){//JULY - DECEMBER
           targetMonth = targetMonth - 5;
       }else{//JANUARY - JUNE
           targetMonth = targetMonth + 7;
           targetYear = targetYear - 1;
       }
       System.out.println("Month INT: "+Calendar.getInstance().get(Calendar.MONTH));
       for(int i = 0; i< tahuns.size(); i++){
           tunggakanPascaFilters.add(new TunggakanPasca(profil.noInduk, new Level(null,null,null,tahuns.get(i)), entries));
           
        }
       Map<Long, TunggakanPasca> searchResultMap = Control.exactFilterSelectIurans(Iuran.Tipe.TunggakanPasca, tunggakanPascaFilters);
        if(searchResultMap.size() > 0){
            for(Map.Entry<Long, TunggakanPasca> entry: searchResultMap.entrySet()){
                for(int j =0 ; j< entry.getValue().entries.size(); j++){
                    if((entry.getValue().entries.get(j).transactDetailIDs.isEmpty()) 
                            && ((entry.getValue().chargedLevel.tahun < targetYear)? true:(entry.getValue().entries.get(j).period <= targetMonth))){
                        retVal += entry.getValue().entries.get(j).amount;
                    }else if(entry.getValue().entries.get(j).transactDetailIDs.size() > 0){
                        Float temp = 0f;
                        for(Long l : entry.getValue().entries.get(j).transactDetailIDs){
                            temp += Control.selectTDetail(TransactionDetail.Tipe.TunggakanPascaTransaction, l).amount;
                        }
                        if(temp < entry.getValue().entries.get(j).amount){
                            retVal += entry.getValue().entries.get(j).amount-temp;
                        } 
                    }
                }
            }
        }
       unpaidTunggakanPasca = retVal;
       return retVal;
    }
    
    public ArrayList<TunggakanBean> calculateUnpaidTunggakanPascas(ArrayList<Profil> profils, List<Integer> tahuns) throws SQLException, KasirException {
       Set<TunggakanPasca> tunggakanPascaFilters = new HashSet<>();
       ArrayList<TunggakanBean> retVals = new ArrayList<>();
       float retVal = 0;
       ArrayList<Entry> entries = new ArrayList<>();
       tunggakanPascaFilters.clear();
       int targetMonth = Calendar.getInstance().get(Calendar.MONTH);
       int targetYear = Calendar.getInstance().get(Calendar.YEAR);
       if(targetMonth>5){//JULY - DECEMBER
           targetMonth = targetMonth - 5;
       }else{//JANUARY - JUNE
           targetMonth = targetMonth + 7;
           targetYear = targetYear - 1;
       }
       System.out.println("Month INT: "+Calendar.getInstance().get(Calendar.MONTH));
       ArrayList<String> noInduks = new ArrayList<>();
       for(int i = 0; i< profils.size() ; i++){
           noInduks.add(profils.get(i).noInduk);
            for(int j = 0; j< tahuns.size(); j++){
                tunggakanPascaFilters.add(new TunggakanPasca(profils.get(i).noInduk, new Level(null,null,null,tahuns.get(j)), entries));

            }
       }
       List<TunggakanPasca> test = Control.selectIurans(Iuran.Tipe.TunggakanPasca, TunggakanPasca.noIndukColName, false, noInduks.toArray(new String[0]));
       
       for(int i = 0 ; i< test.size(); i++){
           TunggakanBean tb = new TunggakanBean();
           for(int j = 0 ; j < test.get(i).entries.size(); j++){
               if(j==0) retVal=0;
               Float totalAmountTunggakanPascaTDetails = 0f;
               for(Long l : test.get(i).entries.get(j).transactDetailIDs){
                   totalAmountTunggakanPascaTDetails += Control.selectTDetail(TransactionDetail.Tipe.TunggakanPascaTransaction, l).amount;
               }
               if((totalAmountTunggakanPascaTDetails < test.get(i).entries.get(j).amount)
                   && ((test.get(i).chargedLevel.tahun < targetYear? true: (test.get(i).entries.get(j).period <= targetMonth)))){
                    
                            
                            retVal += test.get(i).entries.get(j).amount-totalAmountTunggakanPascaTDetails;
                            tunggakanTunggakanPascaString = tunggakanTunggakanPascaString.concat("TunggakanPasca Bulan ");
                            tunggakanTunggakanPascaString = tunggakanTunggakanPascaString.concat(getMonthName(test.get(i).entries.get(j).period));
                            tunggakanTunggakanPascaString = tunggakanTunggakanPascaString.concat(" "+String.valueOf(test.get(i).chargedLevel.tahun)+"/"+String.valueOf(1+test.get(i).chargedLevel.tahun));
                            tunggakanTunggakanPascaString = tunggakanTunggakanPascaString.concat("\r\n");
                            
                            tunggakanTunggakanPascaEachAmountString = tunggakanTunggakanPascaEachAmountString.concat("Rp. ");
                            tunggakanTunggakanPascaEachAmountString = tunggakanTunggakanPascaEachAmountString.concat(String.valueOf(Math.round(test.get(i).entries.get(j).amount-totalAmountTunggakanPascaTDetails)));
                            tunggakanTunggakanPascaEachAmountString = tunggakanTunggakanPascaEachAmountString.concat("\r\n");
               }
               
                
               
               
           }
           tb.setProfil(profils.get(i));
           tb.setTunggakanTunggakanPasca(retVal);
           retVals.add(tb);
           System.out.println(test.get(i).noInduk);
       }
       unpaidTunggakanPasca = retVal;
       return retVals;
    }
   
    private String getMonthName(int p){
        String ret;
        switch(p){
            case 1: ret = "JULI";
                break;
            case 2: ret = "AGUSTUS";
                break;
            case 3: ret = "SEPTEMBER";
                break;
            case 4: ret = "OKTOBER";
                break;
            case 5: ret = "NOPEMBER";
                break;
            case 6: ret = "DESEMBER";
                break;
            case 7: ret = "JANUARI";
                break;
            case 8: ret = "FEBRUARI";
                break;
            case 9: ret = "MARET";
                break;
            case 10: ret = "APRIL";
                break;
            case 11: ret = "MEI";
                break;
            case 12: ret = "JUNI";
                break;
            default: ret = "Invalid";
                break;
        }
        return ret;
        
    }

    public boolean isTunggakanPascaEnough(Set<Long> transactDetailIDs, float amountTunggakanPascainTable) throws SQLException, KasirException {
        Float totalAmountTDetail = 0f;
        for(Long l : transactDetailIDs){
            totalAmountTDetail += Control.selectTDetail(TransactionDetail.Tipe.TunggakanPascaTransaction, l).amount;
        }
        if(totalAmountTDetail < amountTunggakanPascainTable){
            return false;
        }else{
            return true;
        }
    }
    
    
    public float calculatePaidTunggakanPasca(Set<Long> transactDetailIDs) throws SQLException, KasirException{
        Float retVal = 0f;
        for(Long l: transactDetailIDs){
            retVal += Control.selectTDetail(TransactionDetail.Tipe.TunggakanPascaTransaction, l).amount;
        }
        return retVal;
    }
    
}
