/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import iuran.IPSB;
import iuran.Iuran;
import java.sql.SQLException;
import java.text.ParseException;
import javax.swing.JOptionPane;
import kasir.Control;
import org.openide.util.Exceptions;
import pelajar.Profil;
import sak.KasirException;

/**
 *
 * @author Master
 */
public class InputTransactionIPSB extends javax.swing.JFrame {
    private IPSB ipsb;
    private IPSB ipsbFromDB;
    private IPSB ipsbStoreToDB;
    private IPSB ipsbCurrent;
    private float minIPSB;
    private float maxIPSB;
    public float ipsbTunaiAmount;
    public float ipsbBeasiswaAmount;
    public float ipsbBeasiswaCostAmount;
    private InputTransactionFrameSeparated itfs;
    private Profil profil;
    /**
     * Creates new form InputTransactionIPSB
     */
    public InputTransactionIPSB(Profil profil, InputTransactionFrameSeparated itfs) {
        try {
            this.ipsb = Control.selectIuran(Iuran.Tipe.IPSB, IPSB.noIndukColName, false, profil.noInduk);
            minIPSB = 0F;
            maxIPSB = this.ipsb.amount - this.ipsb.totalInstallment;
            ipsbFromDB = new IPSB();
            ipsbFromDB = this.ipsb;
            ipsbStoreToDB = this.ipsb;
            ipsbCurrent = this.ipsb;
            this.itfs = itfs;
            this.profil = profil;
        } catch (SQLException ex) {
            Exceptions.printStackTrace(ex);
            JOptionPane.showMessageDialog(rootPane, "IPSB Belum Di Setting!\r\n".concat(ex.toString()));
            this.dispose();
        } catch (KasirException ex) {
            Exceptions.printStackTrace(ex);
            JOptionPane.showMessageDialog(rootPane, "IPSB Belum Di Setting!\r\n".concat(ex.toString()));
            this.dispose();
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelIPSP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldIPSBAmount = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldIPSBNote = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldIPSBIuranAmount = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldIPSBSisaAmount = new javax.swing.JTextField();
        jButtonIPSBOK = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldIPSBTunai = new javax.swing.JTextField();
        jTextFieldIPSBBeasiswa = new javax.swing.JTextField();
        jTextFieldIPSBBeasiswaCost = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(480, 500));

        jPanelIPSP.setMinimumSize(new java.awt.Dimension(440, 480));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText(org.openide.util.NbBundle.getMessage(InputTransactionIPSB.class, "InputTransactionIPSB.jLabel1.text")); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(InputTransactionIPSB.class, "InputTransactionIPSB.jLabel3.text")); // NOI18N

        jTextFieldIPSBIuranAmount.setEditable(false);
        jTextFieldIPSBAmount.setEditable(false);
        jTextFieldIPSBAmount.setText(org.openide.util.NbBundle.getMessage(InputTransactionIPSB.class, "InputTransactionIPSB.jTextFieldIPSBAmount.text")); // NOI18N
        jTextFieldIPSBAmount.setName(org.openide.util.NbBundle.getMessage(InputTransactionIPSB.class, "InputTransactionIPSB.jTextFieldIPSBAmount.name")); // NOI18N
        jTextFieldIPSBAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIPSBAmountActionPerformed(evt);
            }
        });
        jTextFieldIPSBAmount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldIPSBAmountFocusLost(evt);
            }
        });
        jTextFieldIPSBAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIPSBAmountKeyTyped(evt);
            }
        });

        jLabel5.setText(org.openide.util.NbBundle.getMessage(InputTransactionIPSB.class, "InputTransactionIPSB.jLabel5.text")); // NOI18N

        jTextFieldIPSBNote.setText(org.openide.util.NbBundle.getMessage(InputTransactionIPSB.class, "InputTransactionIPSB.jTextFieldIPSBNote.text")); // NOI18N

        jLabel13.setText(org.openide.util.NbBundle.getMessage(InputTransactionIPSB.class, "InputTransactionIPSB.jLabel13.text")); // NOI18N

        jTextFieldIPSBIuranAmount.setEditable(false);
        jTextFieldIPSBIuranAmount.setText(String.valueOf(ipsb.amount));
        jTextFieldIPSBIuranAmount.setFocusable(false);
        jTextFieldIPSBIuranAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIPSBIuranAmountActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText(org.openide.util.NbBundle.getMessage(InputTransactionIPSB.class, "InputTransactionIPSB.jLabel17.text")); // NOI18N

        jTextFieldIPSBSisaAmount.setEditable(false);
        jTextFieldIPSBSisaAmount.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextFieldIPSBSisaAmount.setText(String.valueOf(maxIPSB));
        jTextFieldIPSBSisaAmount.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldIPSBSisaAmount.setFocusable(false);
        jTextFieldIPSBSisaAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIPSBSisaAmountActionPerformed(evt);
            }
        });

        jButtonIPSBOK.setText(org.openide.util.NbBundle.getMessage(InputTransactionIPSB.class, "InputTransactionIPSB.jButtonIPSBOK.text")); // NOI18N
        jButtonIPSBOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIPSBOKActionPerformed(evt);
            }
        });

        jLabel2.setText(org.openide.util.NbBundle.getMessage(InputTransactionIPSB.class, "InputTransactionIPSB.jLabel2.text")); // NOI18N

        jLabel4.setText(org.openide.util.NbBundle.getMessage(InputTransactionIPSB.class, "InputTransactionIPSB.jLabel4.text_2")); // NOI18N

        jLabel6.setText(org.openide.util.NbBundle.getMessage(InputTransactionIPSB.class, "InputTransactionIPSB.jLabel6.text_2")); // NOI18N

        jTextFieldIPSBTunai.setText(org.openide.util.NbBundle.getMessage(InputTransactionIPSB.class, "InputTransactionIPSB.jTextFieldIPSBTunai.text")); // NOI18N
        jTextFieldIPSBTunai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIPSBTunaiActionPerformed(evt);
            }
        });
        jTextFieldIPSBTunai.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldIPSBTunaiFocusLost(evt);
            }
        });
        jTextFieldIPSBTunai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIPSBTunaiKeyTyped(evt);
            }
        });

        jTextFieldIPSBBeasiswa.setText(org.openide.util.NbBundle.getMessage(InputTransactionIPSB.class, "InputTransactionIPSB.jTextFieldIPSBBeasiswa.text")); // NOI18N
        jTextFieldIPSBBeasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIPSBBeasiswaActionPerformed(evt);
            }
        });
        jTextFieldIPSBBeasiswa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldIPSBBeasiswaFocusLost(evt);
            }
        });
        jTextFieldIPSBBeasiswa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIPSBBeasiswaKeyTyped(evt);
            }
        });

        jTextFieldIPSBBeasiswaCost.setText(org.openide.util.NbBundle.getMessage(InputTransactionIPSB.class, "InputTransactionIPSB.jTextFieldIPSBBeasiswaCost.text")); // NOI18N
        jTextFieldIPSBBeasiswaCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIPSBBeasiswaCostActionPerformed(evt);
            }
        });
        jTextFieldIPSBBeasiswaCost.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldIPSBBeasiswaCostFocusLost(evt);
            }
        });
        jTextFieldIPSBBeasiswaCost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIPSBBeasiswaCostKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanelIPSPLayout = new javax.swing.GroupLayout(jPanelIPSP);
        jPanelIPSP.setLayout(jPanelIPSPLayout);
        jPanelIPSPLayout.setHorizontalGroup(
            jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIPSPLayout.createSequentialGroup()
                .addGroup(jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelIPSPLayout.createSequentialGroup()
                        .addGroup(jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel13)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(11, 11, 11)
                        .addGroup(jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldIPSBNote, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelIPSPLayout.createSequentialGroup()
                                .addGroup(jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldIPSBAmount, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldIPSBIuranAmount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel17)
                                .addGap(12, 12, 12)
                                .addComponent(jTextFieldIPSBSisaAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))))
                    .addGroup(jPanelIPSPLayout.createSequentialGroup()
                        .addGroup(jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanelIPSPLayout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(jButtonIPSBOK))
                            .addGroup(jPanelIPSPLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldIPSBBeasiswaCost, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                    .addGroup(jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldIPSBBeasiswa)
                                        .addComponent(jTextFieldIPSBTunai, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelIPSPLayout.setVerticalGroup(
            jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIPSPLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addGroup(jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldIPSBIuranAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jTextFieldIPSBSisaAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldIPSBAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldIPSBTunai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldIPSBBeasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldIPSBBeasiswaCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelIPSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldIPSBNote, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonIPSBOK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelIPSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelIPSP, javax.swing.GroupLayout.PREFERRED_SIZE, 302, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIPSBAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIPSBAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIPSBAmountActionPerformed

    private void jTextFieldIPSBAmountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldIPSBAmountFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextFieldIPSBAmountFocusLost

    private void jTextFieldIPSBAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIPSBAmountKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextFieldIPSBAmountKeyTyped

    private void jTextFieldIPSBIuranAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIPSBIuranAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIPSBIuranAmountActionPerformed

    private void jTextFieldIPSBSisaAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIPSBSisaAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIPSBSisaAmountActionPerformed

    private void jButtonIPSBOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIPSBOKActionPerformed
        // TODO add your handling code here:
        itfs.jTextFieldIPSBAmountSimple.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));

        try {
            itfs.jTextFieldIPSBAmountSimple.setValue(Float.valueOf(jTextFieldIPSBAmount.getText()));
            itfs.jTextFieldIPSBAmountSimple.commitEdit();
        } catch (ParseException ex) {
            Exceptions.printStackTrace(ex);
        }
        itfs.ipsbFromDB = this.ipsbFromDB;
        itfs.ipsbStoreToDB = this.ipsbStoreToDB;
        itfs.ipsbCurrent = this.ipsbCurrent;
//        try {
//            ipsb = Control.selectIuran(Iuran.Tipe.IPSB, IPSB.noIndukColName, false, profil.noInduk);
//            itfs.ipsb = ipsb;
//        } catch (SQLException ex) {
//            //idd = null;
//        } catch (KasirException ex) {
//            //idd = null;
//        }
        this.setVisible(false);
    }//GEN-LAST:event_jButtonIPSBOKActionPerformed

    private void jTextFieldIPSBBeasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIPSBBeasiswaActionPerformed
        // TODO add your handling code here:
        calculateIPSBAmount();
    }//GEN-LAST:event_jTextFieldIPSBBeasiswaActionPerformed

    private void jTextFieldIPSBTunaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIPSBTunaiActionPerformed
        // TODO add your handling code here:
        calculateIPSBAmount();
    }//GEN-LAST:event_jTextFieldIPSBTunaiActionPerformed

    private void jTextFieldIPSBTunaiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIPSBTunaiKeyTyped
        // TODO add your handling code here:
        calculateIPSBAmount();
    }//GEN-LAST:event_jTextFieldIPSBTunaiKeyTyped

    private void jTextFieldIPSBTunaiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldIPSBTunaiFocusLost
        // TODO add your handling code here:
        calculateIPSBAmount();
    }//GEN-LAST:event_jTextFieldIPSBTunaiFocusLost

    private void jTextFieldIPSBBeasiswaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIPSBBeasiswaKeyTyped
        // TODO add your handling code here:
        calculateIPSBAmount();
    }//GEN-LAST:event_jTextFieldIPSBBeasiswaKeyTyped

    private void jTextFieldIPSBBeasiswaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldIPSBBeasiswaFocusLost
        // TODO add your handling code here:
        calculateIPSBAmount();
    }//GEN-LAST:event_jTextFieldIPSBBeasiswaFocusLost

    private void jTextFieldIPSBBeasiswaCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIPSBBeasiswaCostActionPerformed
        // TODO add your handling code here:
        calculateIPSBAmount();
    }//GEN-LAST:event_jTextFieldIPSBBeasiswaCostActionPerformed

    private void jTextFieldIPSBBeasiswaCostKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIPSBBeasiswaCostKeyTyped
        // TODO add your handling code here:
        calculateIPSBAmount();
    }//GEN-LAST:event_jTextFieldIPSBBeasiswaCostKeyTyped

    private void jTextFieldIPSBBeasiswaCostFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldIPSBBeasiswaCostFocusLost
        // TODO add your handling code here:
        calculateIPSBAmount();
    }//GEN-LAST:event_jTextFieldIPSBBeasiswaCostFocusLost

    private void calculateIPSBAmount(){
        float tunai = Float.valueOf(jTextFieldIPSBTunai.getText());
        float beasiswa = Float.valueOf(jTextFieldIPSBBeasiswa.getText());
        float beasiswaCost = Float.valueOf(jTextFieldIPSBBeasiswaCost.getText());
        ipsbTunaiAmount = tunai;
        ipsbBeasiswaAmount = beasiswa;
        ipsbBeasiswaCostAmount = beasiswaCost;
        jTextFieldIPSBAmount.setText(String.valueOf(tunai+beasiswa+beasiswaCost));
    }
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIPSBOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanelIPSP;
    public javax.swing.JTextField jTextFieldIPSBAmount;
    private javax.swing.JTextField jTextFieldIPSBBeasiswa;
    private javax.swing.JTextField jTextFieldIPSBBeasiswaCost;
    private javax.swing.JTextField jTextFieldIPSBIuranAmount;
    public javax.swing.JTextField jTextFieldIPSBNote;
    private javax.swing.JTextField jTextFieldIPSBSisaAmount;
    private javax.swing.JTextField jTextFieldIPSBTunai;
    // End of variables declaration//GEN-END:variables
}
